# Site settings
title: System-on-Chip Design & Verification
author: Ernesto
  name: Ernesto ALonso Perez
  email: g00436110@atu.ie
description: "A blog."

# Build settings
remote_theme: jekyll/minima
